### ISSUE TITLE
which version is support sonarqube 8.9?

### ISSUE THREAD

**Issue by YuJian95** [javamachr/sonar-gitlab-plugin#21]
hello friend! I would be very grateful if you could let me know that which version is support sonarqube 8.9.

**Comment by jkroepke** [comment]
I'm using 5.1.2 for 8.9 LTS and it works fine.

**Comment by YuJian95** [comment]
> I'm using 5.1.2 for 8.9 LTS and it works fine.

thank you for your answer, I have another question, Is it(version 5.1.2) support Issues mode (Preview)? I have try to do that for some day. my ci-gitlab.yml config in behind .

I want to add sonarqube result to comment in gitlab when I start a pull request. btw, i have add the [branch plugin](https://github.com/mc1arke/sonarqube-community-branch-plugin)(1.8.1)
```
branch_code_analysis:
  stage: branch_code_analysis
  script:
    - mvn clean install -Dmaven.test.skip=true
    - mvn sonar:sonar
      -Dsonar.host.url=sonar_url
      -Dsonar.login=sonar_token
      -Dsonar.projectKey=$CI_PROJECT_NAME
      -Dsonar.pullrequest.key=$CI_MERGE_REQUEST_IID
      -Dsonar.pullrequest.branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
      -Dsonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
      -Dsonar.pullrequest.gitlab.repositorySlug=$CI_PROJECT_ID
      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
      -Dsonar.gitlab.project_id=$CI_PROJECT_PATH
      -Dsonar.gitlab.comment_no_issue=true -X
      -Dsonar.analysis.mode=preview
  tags:
    - mavenrunner02
```

**Comment by jkroepke** [comment]
No idea, we have developer edition.

**Comment by javamachr** [comment]
Preview mode was [removed](https://jira.sonarsource.com/browse/SONAR-11670) in Sonarqube 7.7. This fork is for Sonarqube >= v8.6. If you need older version of sonar(that for example includes preview mode) you have to use [original version](https://github.com/gabrie-allaigre/sonar-gitlab-plugin) that I forked.

**Comment by YuJian95** [comment]
@jkroepke @javamachr Thank you very much.
