### ISSUE TITLE
Question: Is the current version of the plugin compatible with sonarqube 9.9 LTS?

### ISSUE THREAD

**Issue by danilodorgam** [javamachr/sonar-gitlab-plugin#32]
Helloo

First off, thanks for the action. We have been using this action for a very long time 👍

I wanted to ask if the current version of the plugin is compatible with the 9.9 LTS version of SonarQube? Depending on its compatibility, we might update our sonarqube server to 9.9!

Thanks!

**Comment by javamachr** [comment]
I just release v5.4.0 that should be fine with 9.9
